[package]
name = "database_cracking"
version = "0.1.0"
authors = ["Rob <robmoore121@gmail.com>"]

[dependencies]
rand = "0.3"
time = "*"
bit-vec = "0.4.4"

[lib]
name = "cracking"
path = "src/lib.rs"

[[bin]]
name = "benchmark"
path = "src/bm.rs"
